name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get remove libunwind-14-dev
      - run: sudo apt-get install -y build-essential gettext cmake valac libgee-0.8-dev libsqlite3-dev libgtk-4-dev libnotify-dev libgpgme-dev libsoup2.4-dev libgcrypt20-dev libqrencode-dev libnice-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libsrtp2-dev libadwaita-1-dev libsignal-protocol-c-dev libcanberra-dev
      - run: ./configure --release --no-debug --with-tests --enable-plugin=notification-sound --prefix=/usr --without-webrtc
      - run: cmake --build build
      - run: cmake --build build --target=test
      - name: Build DEB-package
        run: cd build && cpack -G DEB
      - name: Upload Dino+ DEB-package
        uses: actions/upload-artifact@v4
        with:
          name: dino-plus-deb
          path: _packages/dino-plus.deb
      - name: Release Dino+ DEB-package
        if: ${{ github.ref_type == 'tag' }}
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _packages/dino-plus.deb
          asset_name: dino-plus.deb
          tag: ${{ github.ref }}
          release_name: Dino+ ${{ github.ref_name }}

  build-meson:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get remove libunwind-14-dev
      - run: sudo apt-get install -y build-essential gettext libadwaita-1-dev libcanberra-dev libgcrypt20-dev libgee-0.8-dev libgpgme-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgtk-4-dev libnice-dev libnotify-dev libqrencode-dev libsignal-protocol-c-dev libsoup2.4-dev libsqlite3-dev libsrtp2-dev meson valac
      - run: meson setup build -Duse-soup2=true -Dplugin-rtp-webrtc-audio-processing=disabled
      - run: meson compile -C build
      - run: meson test -C build
  build-flatpak:
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - run: flatpak repair --user
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          manifest-path: im.dino.Dino.json
          build-bundle: true
      - name: Release Dino+ flatpak
        if: ${{ github.ref_type == 'tag' }}
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app.flatpak
          asset_name: app.flatpak
          tag: ${{ github.ref }}
          release_name: Dino+ ${{ github.ref_name }}
