name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get remove libunwind-14-dev
      - run: sudo apt-get install -y build-essential gettext cmake valac libgee-0.8-dev libsqlite3-dev libgtk-4-dev libnotify-dev libgpgme-dev libsoup2.4-dev libgcrypt20-dev libqrencode-dev libnice-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libsrtp2-dev libwebrtc-audio-processing-dev libadwaita-1-dev libsignal-protocol-c-dev libcanberra-dev
      - run: ./configure --with-tests --with-libsignal-in-tree
      - run: make
      - run: build/xmpp-vala-test
      - run: build/omemo-test
  build-meson:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get remove libunwind-14-dev
      - run: sudo apt-get install -y build-essential gettext libadwaita-1-dev libcanberra-dev libgcrypt20-dev libgee-0.8-dev libgpgme-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgtk-4-dev libnice-dev libnotify-dev libqrencode-dev libsignal-protocol-c-dev libsoup2.4-dev libsqlite3-dev libsrtp2-dev libwebrtc-audio-processing-dev meson valac
      - run: meson setup build -Dcrypto-backend=auto -Dplugin-ice=enabled -Duse-soup2=true
      - run: meson compile -C build
      - run: build/plugins/omemo/test_omemo
  build-flatpak:
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - run: flatpak repair --user
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          manifest-path: im.dino.Dino.json
          build-bundle: true
      - name: Release Dino installer
        if: ${{ github.ref_type == 'tag' }}
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app.flatpak
          asset_name: app.flatpak
          tag: ${{ github.ref }}
          release_name: Dino ${{ github.ref_name }}
